# Based from my personal configuration
parserOptions:
  # Ensure this is consistent with the compiler options
  ecmaVersion: 2015
  sourceType: "module"
  project: [ "./tsconfig.json" ]
  tsconfigRootDir: "."
env:
  browser: true
  es6: true
  node: true
plugins:
  - "@typescript-eslint"
parser: "@typescript-eslint/parser"
extends:
  - "eslint:all"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
  - "whitelistyle"
