# Based from my personal configuration
parserOptions:
  # Ensure this is consistent with the compiler options
  ecmaVersion: 2015
  sourceType: "module"
env:
  browser: true
  es6: true
  node: true
plugins:
  - "@typescript-eslint"
extends:
  - "plugin:@typescript-eslint/recommended"
  - "whitelistyle"
