parserOptions:
  ecmaVersion: 2020
  sourceType: "module"
env:
  browser: true
  es6: true
  node: true
  jest: true
plugins:
  - "@typescript-eslint"
extends:
  - "plugin:@typescript-eslint/recommended"
  - "whitelistyle"
