import { IS_INDEXABLE } from "$env/static/private"
import { PUBLIC_PRODUCTION_BASE_URL } from "$env/static/public"

import metaCollection from "@/constants/meta_collection"
import redirectedMetaCollection from "@/constants/redirected_meta_collection"

// eslint-disable-next-line @typescript-eslint/require-await
export async function GET() {
	const robotsPath = "/robots.txt"
	const sitemapPath = "/sitemap.xml"
	const icon = "/favicon.png"
	const documentPaths = IS_INDEXABLE === "true"
		? [ ...metaCollection, ...redirectedMetaCollection ].map(meta => meta.path)
		: []

	/*
	 * Auto-generated files are not indexed anyway as headers were configured automatically by the
	 * meta framework.
	 */
	const autoGenerated = "/_app/"
	const APIRoutes = "/api/"
	const allowRules = [
		...[ autoGenerated, APIRoutes ].map(path => `Allow: ${path}`),
		...[ icon, robotsPath, sitemapPath, ...documentPaths ].map(path => `Allow: ${path}$`)
	]
	const compiledAllowRules = allowRules.join("\n")

	const sitemapRules = [ `Sitemap: ${PUBLIC_PRODUCTION_BASE_URL}${sitemapPath}` ]
	const compiledSitemapRules = sitemapRules.join("\n")

	const userAgentRules = [
		"User-agent: *",
		compiledAllowRules,
		"Disallow: /"
	]
	const compiledUserAgentRules = userAgentRules.filter(Boolean).join("\n")

	return new Response(
		`
		${compiledUserAgentRules}

		${compiledSitemapRules}
		`.trim()
			.replace(/\t+/gu, ""),
		{
			"headers": {
				"Content-Type": "text/plain"
			}
		}
	)
}
