name: E2E Tests

on:
  push: []
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - review_requested
    branches:
      - master
      - dev
    paths:
      - 'package.json'
      - '.env.ci'
      - 'vite.config.ts'
      - 'svelte.config.js'
      - 'tsconfig.json'
      - 'postcss.config.cjs'
      - 'tailwind.config.cjs'
      - 'src/**'
      - 't/**'
      - '.github/workflows/e2e.yml'

jobs:
  e2e_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Testing on Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Treat .env.ci as the environment for CI
      run: cp .env.ci .env
    - name: Install general dependencies
      run: npm install
    - name: Install dependencies to do E2E tests
      run: npm run test:e2e:install
    - name: Install dependencies to check grammar
      run: npx gramma server install
    - name: Run the tests
      run: npm run test:e2e
